export const UI_TEXT = {
  API: {
    FALLBACK_ERROR: "Something went wrong",
  },
  AUTH: {
    BACK: "Back",
    CONFIRM_PASSWORD: "Confirm password",
    CONTINUE: "Continue",
    CREATE_ACCOUNT: "Create account",
    DEPARTMENT: "Department",
    EMAIL: "Email",
    HIDE_PASSWORD: "Hide password",
    JOIN_DATE: "Join date",
    LOGIN_FOOTER_LABEL: "Create one",
    LOGIN_FOOTER_TEXT: "Need an employee account?",
    LOGIN_TITLE: "Sign in",
    LOGOUT_CANCEL: "Cancel",
    LOGOUT_CONFIRM: "Logout",
    LOGOUT_DESCRIPTION:
      "You will need to sign in again to access your account.",
    LOGOUT: "Logout",
    LOGOUT_SUCCESS: "Logged out successfully",
    LOGOUT_TITLE: "Logout?",
    NAME: "Name",
    PASSWORD: "Password",
    REGISTER_FOOTER_LABEL: "Sign in",
    REGISTER_FOOTER_TEXT: "Already registered?",
    REGISTER_TITLE: "Employee registration",
    SHOW_PASSWORD: "Show password",
    SIGN_IN: "Sign in",
  },
  PLACEHOLDER: {
    CONFIRM_PASSWORD: "Re-enter your password",
    DEPARTMENT: "Engineering",
    EMAIL: "name@company.com",
    JOIN_DATE: "Select join date",
    NAME: "Enter your full name",
    PASSWORD: "Enter your password",
  },
  META: {
    DESCRIPTION: "Employee and admin leave management system",
    TITLE: "Leave Management",
  },
  NAV: {
    ADMIN_DASHBOARD: "Dashboard",
    ADMIN_REQUESTS: "Requests",
    APPLY: "Apply leave",
    DASHBOARD: "Dashboard",
    LOGOUT: "Logout",
    MENU_LABEL: "Main navigation",
    MY_LEAVES: "My leaves",
  },
  PLACEHOLDERS: {
    ADMIN_DASHBOARD_BODY:
      "Organization leave stats will be connected after the leave API step.",
    ADMIN_DASHBOARD_TITLE: "Admin dashboard",
    ADMIN_REQUESTS_BODY:
      "Approval workflows will be connected after the leave API step.",
    ADMIN_REQUESTS_TITLE: "All requests",
    APPLY_BODY:
      "The leave application form will be connected after the leave API step.",
    APPLY_TITLE: "Apply leave",
    EMPLOYEE_DASHBOARD_BODY:
      "Leave balance and recent requests will be connected in the leave step.",
    EMPLOYEE_DASHBOARD_TITLE: "Employee dashboard",
    MY_LEAVES_BODY:
      "Your leave history will be connected after the leave API step.",
    MY_LEAVES_TITLE: "My leaves",
  },
  LEAVE: {
    ADMIN_COMMENT: "Admin comment",
    ADMIN_COMMENT_PLACEHOLDER: "Add an optional comment",
    APPROVE: "Approve",
    APPROVE_REQUEST: "Approve request",
    APPLY_SUBMIT: "Submit request",
    BALANCE_CARD_TITLE: "Remaining balance",
    BALANCE_DAYS: "days",
    CASUAL: "Casual",
    DASHBOARD_RECENT_TITLE: "Recent requests",
    DELETE_DESCRIPTION:
      "This action cannot be undone. Approved leave days will be restored to the employee balance.",
    DELETE_REQUEST: "Delete request",
    DELETE_REQUEST_CONFIRM: "Delete",
    EDIT_REQUEST: "Edit request",
    EMPTY_RECENT: "No leave requests yet.",
    EMPTY_TABLE: "No leave requests found.",
    END_DATE: "End date",
    EARNED: "Earned",
    LEAVE_TYPE: "Leave type",
    LOADING_REQUESTS: "Loading requests...",
    MY_LEAVES_TITLE: "Leave history",
    REJECT: "Reject",
    REJECT_REQUEST: "Reject request",
    REASON: "Reason",
    SICK: "Sick",
    START_DATE: "Start date",
    TABLE_DAYS: "Days",
    TABLE_END_DATE: "End date",
    TABLE_REASON: "Reason",
    TABLE_START_DATE: "Start date",
    TABLE_STATUS: "Status",
    TABLE_TYPE: "Type",
    TOTAL_DAYS: "Total days",
    VIEW_REQUEST: "View request",
  },
  ADMIN: {
    ACTIONS: "Actions",
    ALL: "All",
    APPROVED: "Approved",
    EMPLOYEE: "Employee",
    FILTER_STATUS: "Status",
    FILTER_TYPE: "Type",
    PENDING: "Pending",
    REJECTED: "Rejected",
    REQUESTS_TITLE: "All leave requests",
    STAT_APPROVED: "Approved",
    STAT_EMPLOYEES: "Employees",
    STAT_PENDING: "Pending",
    STAT_REJECTED: "Rejected",
    STAT_TOTAL: "Total requests",
    VIEW: "View",
    EDIT: "Edit",
    DELETE: "Delete",
  },
  LEAVE_PLACEHOLDER: {
    REASON: "Share the reason for this leave request",
  },
  THEME: {
    LABEL: "Toggle theme",
  },
  VALIDATION: {
    CONFIRM_PASSWORD_MATCH: "Passwords must match",
    DEPARTMENT_MIN: "Department must be at least 2 characters",
    EMAIL_REQUIRED: "Email is required",
    JOIN_DATE_REQUIRED: "Join date is required",
    NAME_MIN: "Name must be at least 2 characters",
    PASSWORD_MIN: "Password must be at least 6 characters",
    REASON_MIN: "Reason must be at least 10 characters",
    SELECT_LEAVE_TYPE: "Select a leave type",
    START_DATE_REQUIRED: "Start date is required",
    END_DATE_REQUIRED: "End date is required",
    END_DATE_BEFORE_START_DATE: "End date must be equal to or after start date",
    INSUFFICIENT_BALANCE: "Requested days exceed remaining balance",
  },
} as const;
